@ComprasVentas_HostAddress = http://localhost:5171

GET {{ComprasVentas_HostAddress}}/api/categoria
Accept: application/json

### Get categoria By Id
GET {{ComprasVentas_HostAddress}}/api/categoria/2
Accept: application/json


###
POST {{ComprasVentas_HostAddress}}/api/categoria
Content-Type: application/json
Accept: application/json

{
    "Nombre": "Categoria 2",
    "Descripcion": "dasdsadsadsadsadas2"
}

###
PUT {{ComprasVentas_HostAddress}}/api/categoria/3
Content-Type: application/json
Accept: application/json

{
    "Nombre": "Categoria 2 upd",
    "Descripcion": "dasdsadsadsadsadas2 upd"
}

### Delete categoria By Id
DELETE {{ComprasVentas_HostAddress}}/api/categoria/3
Accept: application/json

### Get usuario By Id
GET {{ComprasVentas_HostAddress}}/api/usuario/33
Accept: application/json

### Create usuario
POST {{ComprasVentas_HostAddress}}/api/usuario
Content-Type: application/json
Accept: application/json

{
    "Username": "Categoria 2",
    "Email": "test@test.com",
    "Password": "passworD1!",
    "Nombres": "dasdsadsad sadsadas2",
    "Apellidos": "dasdsadsa dsadsadas2",
    "FechaNacimiento": "01/01/2000",
    "Genero": "dasdsadsadsads",
    "Telefono": "dasdsadsadsads",
    "Direccion": "dasdsadsadsadsa",
    "Nacionalidad": "dasdsadsadsad"
}
