// <auto-generated />
using System;
using ComprasVentas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ComprasVentas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260628021357_CompleteProj")]
    partial class CompleteProj
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComprasVentas.Almacen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("integer")
                        .HasColumnName("sucursal_id");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_almacenes");

                    b.HasIndex("SucursalId")
                        .HasDatabaseName("ix_almacenes_sucursal_id");

                    b.ToTable("almacenes");
                });

            modelBuilder.Entity("ComprasVentas.AlmacenProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlmacenId")
                        .HasColumnType("integer")
                        .HasColumnName("almacen_id");

                    b.Property<int>("CantidadActual")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_actual");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<decimal>("PrecioVentaActual")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_venta_actual");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("pk_almacen_productos");

                    b.HasIndex("AlmacenId")
                        .HasDatabaseName("ix_almacen_productos_almacen_id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_almacen_productos_producto_id");

                    b.ToTable("almacen_productos");
                });

            modelBuilder.Entity("ComprasVentas.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_nombre");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("ComprasVentas.ClienteProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<string>("NroIdentificacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nro_identificacion");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razon_social");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_cliente_proveedor");

                    b.ToTable("cliente_proveedor");
                });

            modelBuilder.Entity("ComprasVentas.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionDoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion_doc");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("referencia");

                    b.HasKey("Id")
                        .HasName("pk_documentos");

                    b.HasIndex("PersonaId")
                        .HasDatabaseName("ix_documentos_persona_id");

                    b.ToTable("documentos");
                });

            modelBuilder.Entity("ComprasVentas.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlmacenId")
                        .HasColumnType("integer")
                        .HasColumnName("almacen_id");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric")
                        .HasColumnName("cantidad");

                    b.Property<int>("NotaId")
                        .HasColumnType("integer")
                        .HasColumnName("nota_id");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("PrecioUnitarioCompra")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_unitario_compra");

                    b.Property<decimal>("PrecioUnitarioVenta")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_unitario_venta");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_movimiento");

                    b.HasKey("Id")
                        .HasName("pk_movimientos");

                    b.HasIndex("AlmacenId")
                        .HasDatabaseName("ix_movimientos_almacen_id");

                    b.HasIndex("NotaId")
                        .HasDatabaseName("ix_movimientos_nota_id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_movimientos_producto_id");

                    b.ToTable("movimientos");
                });

            modelBuilder.Entity("ComprasVentas.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteProveedorId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_proveedor_id");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("numeric")
                        .HasColumnName("descuento");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Impuestos")
                        .HasColumnType("numeric")
                        .HasColumnName("impuestos");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("TipoNota")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_nota");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_notas");

                    b.HasIndex("ClienteProveedorId")
                        .HasDatabaseName("ix_notas_cliente_proveedor_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_notas_usuario_id");

                    b.ToTable("notas");
                });

            modelBuilder.Entity("ComprasVentas.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Recurso")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recurso");

                    b.HasKey("Id")
                        .HasName("pk_permisos");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_permisos_nombre");

                    b.ToTable("permisos");
                });

            modelBuilder.Entity("ComprasVentas.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("direccion");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Genero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("genero");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("text")
                        .HasColumnName("nacionalidad");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_personas");

                    b.ToTable("personas");
                });

            modelBuilder.Entity("ComprasVentas.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Imagen")
                        .HasColumnType("text")
                        .HasColumnName("imagen");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("marca");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioVentaActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_venta_actual");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidad_medida");

                    b.HasKey("Id")
                        .HasName("pk_productos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_productos_categoria_id");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("ComprasVentas.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime>("Expires")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<bool>("IsActive")
                        .HasMaxLength(100)
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("ComprasVentas.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_nombre");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("ComprasVentas.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_sucursales");

                    b.ToTable("sucursales");
                });

            modelBuilder.Entity("ComprasVentas.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_nombre");

                    b.HasIndex("PersonaId")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_persona_id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.Property<int>("PermisosId")
                        .HasColumnType("integer")
                        .HasColumnName("permisos_id");

                    b.Property<int>("RolesId")
                        .HasColumnType("integer")
                        .HasColumnName("roles_id");

                    b.HasKey("PermisosId", "RolesId")
                        .HasName("pk_roles_permisos");

                    b.HasIndex("RolesId")
                        .HasDatabaseName("ix_roles_permisos_roles_id");

                    b.ToTable("roles_permisos", (string)null);
                });

            modelBuilder.Entity("RolUsuario", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("integer")
                        .HasColumnName("roles_id");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarios_id");

                    b.HasKey("RolesId", "UsuariosId")
                        .HasName("pk_usuarios_roles");

                    b.HasIndex("UsuariosId")
                        .HasDatabaseName("ix_usuarios_roles_usuarios_id");

                    b.ToTable("usuarios_roles", (string)null);
                });

            modelBuilder.Entity("SucursalUsuario", b =>
                {
                    b.Property<int>("SucursalesId")
                        .HasColumnType("integer")
                        .HasColumnName("sucursales_id");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarios_id");

                    b.HasKey("SucursalesId", "UsuariosId")
                        .HasName("pk_sucursal_usuario");

                    b.HasIndex("UsuariosId")
                        .HasDatabaseName("ix_sucursal_usuario_usuarios_id");

                    b.ToTable("sucursal_usuario", (string)null);
                });

            modelBuilder.Entity("ComprasVentas.Almacen", b =>
                {
                    b.HasOne("ComprasVentas.Sucursal", "Sucursal")
                        .WithMany("Almacenes")
                        .HasForeignKey("SucursalId")
                        .HasConstraintName("fk_almacenes_sucursales_sucursal_id");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("ComprasVentas.AlmacenProducto", b =>
                {
                    b.HasOne("ComprasVentas.Almacen", "Almacen")
                        .WithMany("AlmacenProductos")
                        .HasForeignKey("AlmacenId")
                        .HasConstraintName("fk_almacen_productos_almacenes_almacen_id");

                    b.HasOne("ComprasVentas.Producto", "Producto")
                        .WithMany("AlmacenProductos")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("fk_almacen_productos_productos_producto_id");

                    b.Navigation("Almacen");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ComprasVentas.Documento", b =>
                {
                    b.HasOne("ComprasVentas.Persona", "Persona")
                        .WithMany("Documentos")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documentos_personas_persona_id");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ComprasVentas.Movimiento", b =>
                {
                    b.HasOne("ComprasVentas.Almacen", "Almacen")
                        .WithMany("Movimientos")
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_almacenes_almacen_id");

                    b.HasOne("ComprasVentas.Nota", "Nota")
                        .WithMany("Movimientos")
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_notas_nota_id");

                    b.HasOne("ComprasVentas.Producto", "Producto")
                        .WithMany("Movimientos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_productos_producto_id");

                    b.Navigation("Almacen");

                    b.Navigation("Nota");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ComprasVentas.Nota", b =>
                {
                    b.HasOne("ComprasVentas.ClienteProveedor", "ClienteProveedor")
                        .WithMany("Notas")
                        .HasForeignKey("ClienteProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notas_cliente_proveedor_cliente_proveedor_id");

                    b.HasOne("ComprasVentas.Usuario", "Usuario")
                        .WithMany("Notas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notas_usuarios_usuario_id");

                    b.Navigation("ClienteProveedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ComprasVentas.Producto", b =>
                {
                    b.HasOne("ComprasVentas.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .HasConstraintName("fk_productos_categorias_categoria_id");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ComprasVentas.RefreshToken", b =>
                {
                    b.HasOne("ComprasVentas.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ComprasVentas.Usuario", b =>
                {
                    b.HasOne("ComprasVentas.Persona", "Persona")
                        .WithOne("Usuario")
                        .HasForeignKey("ComprasVentas.Usuario", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_personas_persona_id");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.HasOne("ComprasVentas.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_permisos_permisos_permisos_id");

                    b.HasOne("ComprasVentas.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_permisos_roles_roles_id");
                });

            modelBuilder.Entity("RolUsuario", b =>
                {
                    b.HasOne("ComprasVentas.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles_roles_roles_id");

                    b.HasOne("ComprasVentas.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles_usuarios_usuarios_id");
                });

            modelBuilder.Entity("SucursalUsuario", b =>
                {
                    b.HasOne("ComprasVentas.Sucursal", null)
                        .WithMany()
                        .HasForeignKey("SucursalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sucursal_usuario_sucursales_sucursales_id");

                    b.HasOne("ComprasVentas.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sucursal_usuario_usuarios_usuarios_id");
                });

            modelBuilder.Entity("ComprasVentas.Almacen", b =>
                {
                    b.Navigation("AlmacenProductos");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("ComprasVentas.ClienteProveedor", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("ComprasVentas.Nota", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("ComprasVentas.Persona", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Usuario")
                        .IsRequired();
                });

            modelBuilder.Entity("ComprasVentas.Producto", b =>
                {
                    b.Navigation("AlmacenProductos");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("ComprasVentas.Sucursal", b =>
                {
                    b.Navigation("Almacenes");
                });

            modelBuilder.Entity("ComprasVentas.Usuario", b =>
                {
                    b.Navigation("Notas");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
